# Generated by Django 4.2.2 on 2023-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_table_position_x_alter_table_position_y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('IN', 'Inactive'), ('AC', 'Active'), ('CP', 'Completed'), ('CN', 'Cancelled')], default='IN', max_length=2),
        ),
    ]
