# Generated by Django 4.2.2 on 2023-06-16 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_reservation_customer'),
        ('user', '0002_remove_customer_first_name_remove_customer_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
